---
name: CD Latest

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io

permissions:
  packages: write


jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
