---
name: Pipeline

on:
  push:
    branches:
      - "*"
      - "**"
    tags:
      - "!*" # This excludes all tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called from other workflows
  workflow_call:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  DEVELOP_BRANCH: develop
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAIN_BRANCH: main
  REGISTRY: ghcr.io

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Requirements
        run: |
          pip install -qr requirements.txt -r requirements-dev.txt
          pip freeze
          pip check

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: router:latest
          scanners: vuln
          trivy-config: trivy.yaml
